### ISSUE TITLE
[discussion] Forms & Form Validation

### ISSUE THREAD

**Issue by jchansen** [lore/lore#156]
### Purpose
The purpose of this issue is to:

1. Recognize that forms and form validation is a common need in app development
2. Document a solution I'm currently using for a project
3. Discuss the interface
4. Discuss whether it should be extracted into an npm module, and if so, whether it should be a generic React package or a lore hook

### Setup & Need
I've been using Lore for a project at work, and the first point the development pace really slowed down was form validation. The app allows people to sign up, manage their account, and essentially browse and edit a catalog of services. This means there are _a lot_ of forms in the application, and finding a simple solution that is trivial to edit (add and remove fields) as the application grows is a must-have.

### Requirements
The application has the following requirements when it comes to form validation:

1. The signup form is a wizard with 3 steps, which means the solution must accommodate a user flow that can validate each step before allowing the user to continue.

2. The signup form has fields for **username** and **email** that must be validated against the server before proceeding to the next step. This means these fields are only valid if **username** and **email** aren't already assigned to an existing account (in other words user input requires triggering an API call)

3. The signup form requires the user to select their **country** and **state/region**. These fields are drop-downs. The **country** field can be pre-populated with options (there are only 248 countries), but the **region** field is too large to pre-populate (contains 4334 regions in the world). So when the user changes the selected **country**, the **region** field needs to fetch and display the associated regions. In other words there is a cascade-type relationship between some fields.

4. Solution can not be specific to the signup form, as other fields in the application (after login) have similar requirements.

### Goals
I want something that feels light weight and simple to integrate, and can easily support wizards in addition to simple editing forms. It also needs to be UI library agnostic (e.g. it can support [Bootstrap](http://getbootstrap.com/) or [Material UI](http://www.material-ui.com/) or _something else_).

Ideally it can work in a non-Lore React app, but the primary goal is making form development effortless, so including Lore-isms is acceptable if a strong benefit is gained in the process.

### First Draft
I like a lot of the interface for [redux-form](https://github.com/erikras/redux-form), but want something decoupled from Redux, as form state seems strictly like a component-level concern to me. If there's a use case for storing form state globally (in the Redux store) I can't see it at the moment.

This led me to creating something like this:

```jsx
React.createClass({
  displayName: 'FormExample',

  getInitialState: function() {
    username: '',
    password: ''
    confirmPassword: '',
    country: null,
    region: null
  },

  getValidators: function() {
    return {
      username: [
        validators.isRequired, 
        validators.isResolved
      ],
      password: [validators.isRequired],
      confirmPassword: [
        validators.isRequired,
        validators.isEqualTo.bind(null, this.state.password),
      ],
      country: [validators.isRequired],
      region: [validators.isRequired]
    }
  }

  onChange: function(field, value){
    var nextState = {};
    nextState[field] = value;
    this.setState(nextState);
  },

  verifyUsernameIsAvailable: function(getState, props) {
    var username = this.state.username;
    return {
      _model: getState('checkUsername.byId', {
        id: username
      })
    }
  },

  getCountryOptions: function(getState, props) {
    return {
      options: getState('country.find', {
        pagination: {
          page_size: 300
        }
      })
    }
  },
  
  getRegionOptions: function(getState, props) {
    var country = this.state.country;
    return {
      options: getState('region.find', {
        where: {
          country: country
        },
        pagination: {
          page_size: 300
        }
      })
    }
  },

  render: function(){
    return (
      <Form
        data={this.state}
        validators={validators}
        onChange={this.onChange}>
        <FormSection className="row">
          <FormSection className="col-md-12">
            <Connect callback={this.verifyUsernameIsAvailable}>
              <DynamicTextField
                label="Username"
                name="username"
              />
            </Connect>
          </FormSection>
        </FormSection>
        <FormSection className="row">
          <FormSection className="col-md-6">
            <PasswordField
              label="Password"
              name="password"
            />
          </FormSection>
          <FormSection className="col-md-6">
            <PasswordField
              label="Confirm Password"
              name="confirmPassword"
            />
          </FormSection>
        </FormSection>
        <FormSection className="row">
          <FormSection className="col-md-12">
            <Connect callback={this.getCountryOptions}>
              <SelectField
                label="Country"
                name="country"
              />
            </Connect>
          </FormSection>
        </FormSection>
        <FormSection className="row">
          <FormSection className="col-md-12">
            <Connect callback={this.getRegionOptions}>
              <SelectField
                label="State/Region"
                name="region"
              />
            </Connect>
          </FormSection>
        </FormSection>
        <FormNavigation
          onPrevious={this.onPrevious}
          onNext={this.onNext} />
      </Form>
    );
  }

})
```

### Explanation
The `Form` component is responsible for three things:
1. Cloning the child components and passing down the data
2. Running the validators on the data and generating an object or errors, which is then passes down to the child components.
3. Passing down the `onChange` handler that will get invoked when fields modify data.

The `FormSection` component is purely structural. It exists to allow you to inject styling and structure to the form, while continuing to pass down any props received from `Form`.

The various `Field` components (TextField, SelectField, PasswordField) are a library specific implementation of a form field (e.g. Bootstrap, Material UI) that conform to the "Form Interface" as follows.

1. The receive a `data` prop and will extract the value assigned to them using the `name` prop given to them.
2. They receive an object or errors, and will extract and display the error assigned to them (if there is one).
3. They will receive a `onChange` callback that should be invoked when the user changes the value in that field.

The `Connect` component is a light wrapper over `lore.connect` that allows you simplify cascade-type relationships by defining what needs to be fetched at runtime. In this example, that's helpful because which regions we need to provide to the region dropdown will change based on the country selected. So every time the form renders, we get to re-examine the value in `this.state.country` and change the set of region options. Also, because Lore's default behavior is to cache data (using the query as a unique key) we'll only fetch regions once per country, regardless of how many times the form re-renders.

**Comment by timcase** [comment]
### Purpose

The purpose of this comment is to present an approach I'm going to try for handling form validations in Lore. This approach may or may not be the right one for Lore and I'm not advocating that what I'm doing is the way it should be done, but that I'm gonna try this as an independent project and see what happens.

### Setup & Need
Form validation in is difficult because a good UX experience is about informing the user about validation errors at an appropriate time which can be defined as responding to a user's interaction after a value is entered in an input (field level) or the user clicks the submit button (form level) or the user triggers a validation requiring an async call (async level). What makes this interaction tricky is that not only does the validation of the fields need to be calculate but there also needs to be logic that handles when to inform the user of validation errors. Consider the case where an email address is required, at the initial moment when a form is presented to the user it would be inappropriate to show the user an error message saying "email is required" because the user has not yet had the opportunity to enter valid data.

There are 3 cases for informing the user that a validation event is occuring:

1. On blur of field (field level)
2. On submit of form (form level) 
3. On blur of a field that has a validation which requires an async trip to the server. (async level)


### Requirements

Display validity as soon as possible
   -- but not while the user is typing
   -- only after the field was touched
   -- even if validation is not to be displayed, compute it in advance
Handle Async validations
    if async validation is in progress, indicate it
Submit button (or other UI) reflects validity of the form
Validate multiple related fields

### Goals

Implement the requirements described above in a way that abstracts away some of the complexity. A survey of two React validation libraries [React custom validation](https://github.com/vacuumlabs/react-custom-validation) and [Redux forms](https://github.com/erikras/redux-form) shows that the essentially are the same thing done two different ways:

1) The developer creates some sort of validation configuration which describes the fields and the validations to apply against those fields.
2) They change the markup for the form particularly for the input fields it could be by adding props it could be by using custom field components but the purpose is to provide a way for the validations to respond to fields as they change. Same also for the forms submit button, with the difference being that the submit button triggers all the validations for the fields at once.

### First Draft

1. Use react custom validations
2. Create a way to describe validation requirement in lore models
3. Use the validations config in lore dialogs to create forms that also validate.

### Explanation

My idea as of this writing is that React Custom Validations and Redux Forms do the exact same thing but the latter uses Redux. Redux forms is great because it uses redux and it's a terrible because it uses redux. On the plus side you get access to the Redux Devtools so you can inspect the state of your form. On the downside it seems to me to be a bit much to have to rely on Redux for this. I haven't determined if too much in the Redux store is really an issue but stuffing form state in their just feels like pollution to me. For that reason I'm going to use React Custom Validations. (Incidentally I have a work requirement to review both libraries and I'll verify that they are indeed the same thing)

I want to try an add the validation config to Lore models so that describing them isn't that different from describing attributes.

I want to try to modify the lore dialogs so that they not only produce forms based on the attributes but also produce forms that include the markup necessary to validate the fields as well.

**Comment by jchansen** [comment]
@timcase I want to respond more to your write up above, but it'll have to wait until tomorrow. I need to get some sleep.

In the spirit of helping you be successful though, I wrote the first draft of a tutorial for creating a custom hook. You can find it on the development site at this address (I want to take another pass through it before I push it to production):

http://master.lorejs.org/concepts/hooks/tutorial/overview/

The hook I'm using in the tutorial wraps an action and continually invokes it on a timed interval, implementing a very simple form of polling (I'll build a generic more full-featured hook for polling in the future). I tried to think of what things would be relevant to your goals above, so I made sure to include a part about adding custom config values to model definition, and using them in the hook.

You can find the final version of the code in this repo:

https://github.com/lore/lore-hook-tutorial

I'll take another pass through it tomorrow to break up the second step and improve the writing. If you end up looking at it, feel free to request additional explanation/elaboration.

While trying to think of something to build the docs around, I originally tried to come up with a scenario directly relevant to your use case, and have the hook generate React code based on some user-defined model attributes, similar to what it sounds like you want to do for your forms hook. But I couldn't think of anything illustrative short of actually building a hook in a similar vein, which seemed too complex for the docs.

If you'd like to see something like that though, and have an idea about a scenario that would be illustrative but smaller in scope, let me know.

**Comment by jchansen** [comment]
@timcase I updated the tutorial for building custom hooks:

http://master.lorejs.org/concepts/hooks/tutorial/overview/

I'll push to production once I add branches to the project code and update the hook generator to respect project language preference. Will try to tackle that tomorrow.

I also got inspired and built the polling hook for real in #157, along with [an example](https://github.com/lore/lore/tree/master/examples/polling).

As for your form goals, don't hesitate to let me know if there's anything else I can do to help you be successful there. I've got some form code at work I want to experiment with converting into a package or hook, but it's not causing me pain (any more) so it'll probably be at least a week or two before I try something along those lines naturally.

But if there's something you want to see to help you build your package (like an example or conceptual implementation), I can use that as a catalyst to speed up the timeline.

**Comment by timcase** [comment]
Jason Thanks! This is what I needed. I finished doing a deep dive on both react-custom-validations and redux-form and have in the end opted to use redux-form. It works well, and although it does use redux in a way I'm not sure I fully support looking at the numbers it's overwhelmingly the choice for handling form validations, also it was slightly easier to work with.

I quickly looked over the hook tutorial, Thanks for this! I'm gonna use it to see if I can build this form validation hook, if it works I'm all in with Lore (although to be frank I feel like I'm already all in I think you really nailed it).

**Comment by jchansen** [comment]
Closing for the following reasons:

1. I've settled on an approach for forms and dialogs, and built a repo around it called [lore-forms](https://github.com/lore/lore-forms)
2. I've added a tutorial to the updated website that [demonstrates that pattern](http://www.lorejs.org/forms/pattern/)

Also, with addition of the `lore-forms` repo, I'd like to move any form and dialog related discussion to _that_ repo, though questions about custom hooks and model configuration are certainly appropriate for _this_ repo.

Also, considering forms are a huge part of the reason the v0.13 release was delayed so long, it's become clear there needs to be some separation between the two repos in order for Lore to stay focused, and for releases to occur in a timely manner.
