### ISSUE TITLE
Missing figure, list and video?

### ISSUE THREAD

**Issue by baharev** [lore/lore#171]
Based on the text, I would expect an architecture diagram, list of features, and a video on this page:

http://www.lorejs.org/architecture/

however none of these are available. If that page is a work in progress and these things have not been added yet, then please indicate it on the top that page. I personally find this page very confusing at the moment.

**Comment by jchansen** [comment]
@baharev sorry about the confusion, and thanks for letting me know. I added a note to the top of the page ([link](http://www.lorejs.org/architecture/)) that says:

> WARNING! This section is a work in progress. The organization and content may not reflect what you expect and are subject to change. Apologies while it gets sorted out.

Also, I just realized all the architecture links in the "features" subsection were broken, but there actually *are* pages for those with short videos that explains how each feature is supported, like [this one that explains how filtering works](http://www.lorejs.org/architecture/features/filtering/) (5 min). 

I fixed the links if you want to watch them, and I'll include some additional explanation and context below that you might care about if you're poking around the architecture section.

### Site Structure
To be honest, the whole site is a bit of a work in progress. The Quickstart is the most polished, the Features ("how to use it") feels maybe half done, and the Architecture section ("how it's built") has more content missing than present.

When I originally built the site, most of the content I created was focused on explaining how the framework was built and why it was built that way, and the written content was secondary to the videos. The feedback I got basically said "less videos, more writing" and "stop explaining, just tell me how to use it".

In response to that, I removed most of the videos, and broke the site into three sections; a demonstration of what the framework can do (**Quickstart**), documentation for how to use it (**Features**), and a place where I put content that explains design decisions (**Architecture**).

### Architecture
While front-end architecture is the subject I'm most interested in conversing about (Lore is a proof of concept for the underlying ideas) I've accepted at this point that that section will probably be one of the last things that gets updated prior to the v1 release. I haven't found many people interested in engaging/conversing at that level, and since I already understand how the Lore works, it's hard to justify devoting much time to that section without knowing who it benefits.

That being said, there are two goals for the architecture section, which exist in pieces:

1. Explain the patterns Lore is built on, at a pure React/Redux level, in a way such that anyone could implement them without using the framework
2. Explain the architectural layers that make up the `lore.connect` behavior (XMLHttpRequest, Ajax abstraction, REST API abstraction, Redux Action abstraction, Templates to remove boilerplate, Conventions to generate templates).

The first goal exists in part in the short "feature" videos, like the Filtering one above. The biggest thing to note there is that those videos were created a year ago, and anything that says "proposal" is now implemented. Also, the interfaces might have changed slightly, but the underlying concepts haven't.

The second goal (explaining how `connect` works) exists as a [teaser video in the ajax section](http://www.lorejs.org/architecture/ajax-abstraction/) and a more full version of it exists in this 50 minute talk I gave a year ago:

https://www.youtube.com/watch?v=-pMtN6v-vMc

When the timing feels right, I'll create a more polished video of those slides and break it up into 5 or 6 sections and upload them to the website under Architecture. But what exists in the video above represents about 70-80% of what I want to capture about on that subject.

### End
Thanks again for submitting the issue and letting me know about your experience. If you have specific architecture questions, or are evaluating the framework and want to better understand it's limitations or design focus (what it is and what it isn't), feel free to reach out and I'll answer the best I can.

I'm going to close this issue, since I added the "under construction" note to the Architecture page, but feel free to reopen if you want.
